# Generated by Django 2.1 on 2018-08-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
                ('timeframe', models.IntegerField(choices=[(0, 'M1'), (1, 'M5'), (2, 'M15'), (3, 'M30'), (4, 'H1'), (5, 'H4'), (6, 'D1'), (7, 'W1'), (8, 'MN')])),
                ('timestamp', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('tick_volume', models.IntegerField()),
            ],
        ),
    ]
